services:
  sql_server:
    image: gvenzl/oracle-free:23
    container_name: sql_server.g
    hostname: sql_server.g
    restart: no
    network_mode: bridge
    volumes:
      - ./data:/opt/oracle/oradata
      - ./example_tables/:/container-entrypoint-initdb.d
    ports:
      - 1521:1521
    dns:
      - 192.168.1.12
      - 77.88.8.8
      - 77.88.8.1
    environment:
      APP_USER: "root"
      APP_USER_PASSWORD: "root"
      ORACLE_PASSWORD: root

  dbeaver:
    image: dbeaver/cloudbeaver
    container_name: dbeaver.g
    hostname: dbeaver.g
    restart: no
    network_mode: bridge
    dns:
      - 192.168.1.12
      - 77.88.8.8
      - 77.88.8.1
